version: "3"
services:

  testlive_web:
    image: testlive_web
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/opt/app
    command: bash -c "python -m debugpy --listen 0.0.0.0:9000 start.py"
    env_file:
      - .env
    build: .
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=testliver
      - POSTGRES_DB=testlivedb
    ports:
      - "5432:5432"
    restart: always
