"""add_tables

Revision ID: 119bed902ced
Revises: 530e937322f3
Create Date: 2024-02-29 19:14:46.734919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119bed902ced'
down_revision: Union[str, None] = '530e937322f3'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_release',
    sa.Column('id_release', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=180), nullable=False, comment='Name Release'),
    sa.PrimaryKeyConstraint('id_release'),
    schema='tests',
    comment='Test Folder'
    )
    op.create_index(op.f('ix_tests_t_release_id_release'), 't_release', ['id_release'], unique=False, schema='tests')
    op.create_table('t_test_plan',
    sa.Column('id_test_plan', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=180), nullable=True, comment='Playback Steps'),
    sa.Column('id_parent', sa.Integer(), nullable=True, comment='ID Parent'),
    sa.ForeignKeyConstraint(['id_parent'], ['tests.t_test_plan.id_test_plan'], ),
    sa.PrimaryKeyConstraint('id_test_plan'),
    schema='tests',
    comment='Test Folder'
    )
    op.create_index(op.f('ix_tests_t_test_plan_id_parent'), 't_test_plan', ['id_parent'], unique=False, schema='tests')
    op.create_index(op.f('ix_tests_t_test_plan_id_test_plan'), 't_test_plan', ['id_test_plan'], unique=False, schema='tests')
    op.create_table('t_test_status',
    sa.Column('id_test_status', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('code_status', sa.String(length=50), nullable=True, comment='Code Status'),
    sa.Column('name_status', sa.String(length=50), nullable=True, comment='Name Status'),
    sa.PrimaryKeyConstraint('id_test_status'),
    schema='tests',
    comment='Test Folder'
    )
    op.create_index(op.f('ix_tests_t_test_status_id_test_status'), 't_test_status', ['id_test_status'], unique=False, schema='tests')
    op.create_table('t_test_case',
    sa.Column('id_test_case', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('id_test_plan', sa.Integer(), nullable=True, comment='ID Test Plan'),
    sa.Column('name', sa.String(length=180), nullable=False, comment='Name'),
    sa.ForeignKeyConstraint(['id_test_plan'], ['tests.t_test_plan.id_test_plan'], ),
    sa.PrimaryKeyConstraint('id_test_case'),
    schema='tests',
    comment='Test Folder'
    )
    op.create_index(op.f('ix_tests_t_test_case_id_test_case'), 't_test_case', ['id_test_case'], unique=False, schema='tests')
    op.create_index(op.f('ix_tests_t_test_case_id_test_plan'), 't_test_case', ['id_test_plan'], unique=False, schema='tests')
    op.create_table('t_bind_test_release',
    sa.Column('id_bind_test_release', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('id_release', sa.Integer(), nullable=True, comment='ID Release'),
    sa.Column('id_test_case', sa.Integer(), nullable=True, comment='ID Test Case'),
    sa.ForeignKeyConstraint(['id_release'], ['tests.t_release.id_release'], ),
    sa.ForeignKeyConstraint(['id_test_case'], ['tests.t_test_case.id_test_case'], ),
    sa.PrimaryKeyConstraint('id_bind_test_release'),
    schema='tests',
    comment='Bind Test Release'
    )
    op.create_index(op.f('ix_tests_t_bind_test_release_id_bind_test_release'), 't_bind_test_release', ['id_bind_test_release'], unique=False, schema='tests')
    op.create_index(op.f('ix_tests_t_bind_test_release_id_release'), 't_bind_test_release', ['id_release'], unique=False, schema='tests')
    op.create_index(op.f('ix_tests_t_bind_test_release_id_test_case'), 't_bind_test_release', ['id_test_case'], unique=False, schema='tests')
    op.create_table('t_test_step',
    sa.Column('id_test_step', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('id_test_case', sa.Integer(), nullable=True, comment='ID Test Case'),
    sa.Column('number_step', sa.Integer(), nullable=True, comment='Number Step'),
    sa.Column('name_step', sa.Text(), nullable=True, comment='Name Step'),
    sa.Column('playback', sa.Text(), nullable=True, comment='Playback Steps'),
    sa.Column('excepted', sa.Text(), nullable=True, comment='Excepted Result'),
    sa.ForeignKeyConstraint(['id_test_case'], ['tests.t_test_case.id_test_case'], ),
    sa.PrimaryKeyConstraint('id_test_step'),
    schema='tests',
    comment='Test Folder'
    )
    op.create_index(op.f('ix_tests_t_test_step_id_test_step'), 't_test_step', ['id_test_step'], unique=False, schema='tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_t_test_step_id_test_step'), table_name='t_test_step', schema='tests')
    op.drop_table('t_test_step', schema='tests')
    op.drop_index(op.f('ix_tests_t_bind_test_release_id_test_case'), table_name='t_bind_test_release', schema='tests')
    op.drop_index(op.f('ix_tests_t_bind_test_release_id_release'), table_name='t_bind_test_release', schema='tests')
    op.drop_index(op.f('ix_tests_t_bind_test_release_id_bind_test_release'), table_name='t_bind_test_release', schema='tests')
    op.drop_table('t_bind_test_release', schema='tests')
    op.drop_index(op.f('ix_tests_t_test_case_id_test_plan'), table_name='t_test_case', schema='tests')
    op.drop_index(op.f('ix_tests_t_test_case_id_test_case'), table_name='t_test_case', schema='tests')
    op.drop_table('t_test_case', schema='tests')
    op.drop_index(op.f('ix_tests_t_test_status_id_test_status'), table_name='t_test_status', schema='tests')
    op.drop_table('t_test_status', schema='tests')
    op.drop_index(op.f('ix_tests_t_test_plan_id_test_plan'), table_name='t_test_plan', schema='tests')
    op.drop_index(op.f('ix_tests_t_test_plan_id_parent'), table_name='t_test_plan', schema='tests')
    op.drop_table('t_test_plan', schema='tests')
    op.drop_index(op.f('ix_tests_t_release_id_release'), table_name='t_release', schema='tests')
    op.drop_table('t_release', schema='tests')
    # ### end Alembic commands ###
